
import React, { useState, useCallback, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import type { Language, Recipe, UiText, LanguageCode, RecipeList, RecipeSearchResult } from './types';
import { generateRecipe, normalizeGenAIResponse, translateContent } from './services/geminiService';
import { getGenerationCount, recordGeneration, keepAlive, getCachedRecipe, saveRecipeToCache } from './services/firebaseService';
import { getCachedResponse, setCachedResponse } from './services/cacheService';
import Header from './components/Header';
import LanguageSelector from './components/LanguageToggle';
import IngredientInput from './components/IngredientInput';
import RecipeDisplay from './components/RecipeDisplay';
import RecipeListDisplay from './components/RecipeListDisplay';
import LoadingSpinner from './components/LoadingSpinner';
import Footer from './components/Footer';
import ScrollToTopButton from './components/ScrollToTopButton';
import UsageTips from './components/UsageTips';
import GenerationCounter from './components/GenerationCounter';
import FeedbackModal from './components/FeedbackModal';
import AdminModal from './components/AdminModal';
import BackgroundDecorations from './components/BackgroundDecorations';
import ChatWidget from './components/ChatWidget';
import HistoryList from './components/HistoryList';

const LANGUAGES: Language[] = [
  { code: 'ms', name: 'Bahasa Melayu' },
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'zh', name: '中文 (Mandarin)' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'ar', name: 'العربية (Arabic)' },
];

const DEFAULT_UI_TEXT_EN: UiText = {
  headerTitle: "Toma",
  headerSubtitle: "No idea what to cook? Let Toma do the work!",
  inputLabel: "What ingredients do you have?",
  inputPlaceholder: "e.g., chicken, soy sauce, ginger, garlic...",
  generateButton: "Generate Recipe",
  generateButtonLoading: "Generating...",
  searchButton: "Search Recipe",
  searchButtonLoading: "Searching...",
  resetButton: "Reset",
  recipeIngredients: "Ingredients",
  recipeInstructions: "Instructions",
  recipePrepTime: "Prep Time",
  recipeCookTime: "Cook Time",
  recipeTotalTime: "Total Time",
  recipeServings: "Servings",
  exportTitle: "Save Recipe",
  saveAsText: "Save as Text",
  saveAsImage: "Save as Image",
  saveAsPdf: "Save as PDF",
  saveAsImageSaving: "Saving...",
  saveAsPdfSaving: "Saving PDF...",
  errorPrefix: "Failed to generate recipe:",
  errorIngredients: "Please enter some ingredients.",
  loadingMessages: [
    "The AI Chef is thinking...",
    "Chopping onions and chillies...",
    "Heating up the pan...",
    "Finding inspiration at the market...",
    "Checking the secret recipe book...",
    "Almost ready!"
  ],
  translatingMessage: "Translating...",
  tagline: "Your AI Kitchen Assistant",
  usageTips: [
    "Tip: Tap the microphone icon to speak your ingredients!",
    "Tip: List the ingredients you have, like 'chicken, soy sauce, ginger'.",
    "Tip: For a specific dish, just type its name, like 'Nasi Lemak recipe'.",
    "Tip: You can search by Chef name too, try 'Khairul Aming' or 'Chef Wan'!",
    "Tip: You can add constraints, e.g., 'chicken, rice, spicy, quick'.",
    "Tip: Change the language using the toggle at the top right.",
    "Tip: Recipes aren't saved! Use the download buttons to keep them.",
    "Tip: Save your favorite recipes as a PDF for easy printing!",
    "Tip: For custom app inquiries, contact the developer via the feedback link below.",
  ],
  feedbackButton: "Feedback",
  feedbackSubject: "Feedback for Toma App",
  shareTitle: "Share Recipe",
  shareInstructions: "Scan the QR code or copy the link to share this recipe.",
  copyLinkButton: "Copy Link",
  linkCopiedButton: "Copied!",
  generationCounterText: "recipes generated by chefs like you!",
  generationCounterTextSingle: "recipe generated by a chef like you!",
  // Feedback Form EN
  feedbackTitle: "We value your feedback",
  feedbackSubtitle: "Tell us about your experience with Toma",
  labelName: "Name",
  labelEmail: "Email (Optional)",
  labelRating: "Rate your experience",
  labelComment: "Your Review",
  placeholderName: "Your name",
  placeholderEmail: "john@example.com",
  placeholderComment: "What did you like? What can we improve?",
  submitFeedbackButton: "Submit Feedback",
  submittingFeedback: "Submitting...",
  feedbackSuccessTitle: "Thank You!",
  feedbackSuccessMessage: "Your feedback helps us make Toma better.",
  closeButton: "Close",
  // History
  historyTitle: "Recipe History",
  clearHistory: "Clear",
  historyStorageNote: "This data is saved in local storage only.",
  cooldownMessage: "Wait {time}s",
  // PWA
  installButton: "Install App",
  installMessage: "Install Toma for a better experience!",
  
  // Search Results
  searchResultsTitle: "Found Recipes",
  searchResultsSubtitle: "Select a recipe to view details",
  backToResults: "Back to Results",

  // Nutrition EN
  nutritionTitle: "Nutrition Facts",
  caloriesLabel: "Calories",
  proteinLabel: "Protein",
  fatLabel: "Fat",
  carbsLabel: "Carbs",
  vitaminsLabel: "Vitamins",
  mineralsLabel: "Minerals",
  othersLabel: "Other Nutrients",
  healthyTip: "Congratulations on choosing a healthy recipe!",
  unhealthyTip: "You may want to moderate servings of this dish for better health.",
  nutritionDisclaimer: "Nutritional values are estimates based on standard ingredients and portions.",
  showNutrition: "View Nutrition Facts",
  hideNutrition: "Hide Nutrition Facts"
};

const DEFAULT_UI_TEXT_MS: UiText = {
  headerTitle: "Toma",
  headerSubtitle: "Tiada idea nak masak apa? Biar Toma bantu!",
  inputLabel: "Apakah bahan-bahan yang anda ada?",
  inputPlaceholder: "Cth: ayam, kicap, halia, bawang putih...",
  generateButton: "Menjana Resepi",
  generateButtonLoading: "Sedang menjana...",
  searchButton: "Mencari Resepi",
  searchButtonLoading: "Sedang mencari...",
  resetButton: "Set Semula",
  recipeIngredients: "Bahan-Bahan",
  recipeInstructions: "Cara Penyediaan",
  recipePrepTime: "Masa Penyediaan",
  recipeCookTime: "Masa Memasak",
  recipeTotalTime: "Jumlah Masa",
  recipeServings: "Hidangan",
  exportTitle: "Simpan Resepi",
  saveAsText: "Simpan sebagai Teks",
  saveAsImage: "Simpan sebagai Imej",
  saveAsPdf: "Simpan sebagai PDF",
  saveAsImageSaving: "Sedang menyimpan...",
  saveAsPdfSaving: "Menyimpan PDF...",
  errorPrefix: "Gagal menjana resepi:",
  errorIngredients: "Sila masukkan bahan-bahan anda.",
  loadingMessages: [
    "Chef AI sedang berfikir...",
    "Meracik bawang dan cili...",
    "Memanaskan kuali...",
    "Mencari ilham di pasar tani...",
    "Menyemak buku resepi rahsia...",
    "Hampir siap!"
  ],
  translatingMessage: "Menterjemah...",
  tagline: "Chef AI Peribadi Anda",
  usageTips: [
    "Tips: Tekan ikon mikrofon untuk menyebut bahan masakan anda!",
    "Tips: Senaraikan bahan-bahan yang anda ada, cth: 'ayam, kicap, halia'.",
    "Tips: Untuk resepi spesifik, taip nama masakan, cth: 'resepi Nasi Lemak'.",
    "Tips: Anda boleh cari mengikut nama Chef, cuba 'Khairul Aming' atau 'Chef Wan'!",
    "Tips: Anda boleh tambah arahan, cth: 'ayam, nasi, pedas, cepat'.",
    "Tips: Tukar bahasa menggunakan butang di penjuru kanan atas.",
    "Tips: Resepi tidak disimpan! Guna butang muat turun untuk simpan.",
    "Tips: Simpan resepi kegemaran anda sebagai PDF untuk cetakan mudah!",
    "Tips: Untuk tempahan aplikasi, hubungi pembangun melalui pautan maklum balas di bawah.",
  ],
  feedbackButton: "Maklum Balas",
  feedbackSubject: "Maklumbalas Aplikasi Toma",
  shareTitle: "Kongsi Resepi",
  shareInstructions: "Imbas kod QR atau salin pautan untuk kongsi resepi ini.",
  copyLinkButton: "Salin Pautan",
  linkCopiedButton: "Disalin!",
  generationCounterText: "resipi telah dijana oleh chef seperti anda!",
  generationCounterTextSingle: "resipi telah dijana oleh chef seperti anda!",
  // Feedback Form MS
  feedbackTitle: "Maklum balas anda penting",
  feedbackSubtitle: "Kongsikan pengalaman anda bersama Toma",
  labelName: "Nama",
  labelEmail: "Emel (Pilihan)",
  labelRating: "Nilaikan pengalaman anda",
  labelComment: "Ulasan anda",
  placeholderName: "Nama anda",
  placeholderEmail: "ali@contoh.com",
  placeholderComment: "Apa yang anda suka? Apa yang boleh kami perbaiki?",
  submitFeedbackButton: "Hantar Maklum Balas",
  submittingFeedback: "Sedang menghantar...",
  feedbackSuccessTitle: "Terima Kasih!",
  feedbackSuccessMessage: "Maklum balas anda membantu kami menambah baik Toma.",
  closeButton: "Tutup",
  // History
  historyTitle: "Sejarah Resepi",
  clearHistory: "Padam",
  historyStorageNote: "Data ini disimpan dalam local storage sahaja.",
  cooldownMessage: "Tunggu {time}s",
  // PWA
  installButton: "Pasang Aplikasi",
  installMessage: "Pasang Toma untuk pengalaman yang lebih baik!",
  
  // Search Results
  searchResultsTitle: "Resepi Ditemui",
  searchResultsSubtitle: "Pilih resepi untuk lihat butiran",
  backToResults: "Kembali ke Senarai",

  // Nutrition MS
  nutritionTitle: "Fakta Nutrisi",
  caloriesLabel: "Kalori",
  proteinLabel: "Protein",
  fatLabel: "Lemak",
  carbsLabel: "Karbohidrat",
  vitaminsLabel: "Vitamin",
  mineralsLabel: "Mineral",
  othersLabel: "Zat Lain",
  healthyTip: "Tahniah kerana memilih resepi sihat!",
  unhealthyTip: "Anda boleh kurangkan hidangan seperti ini untuk kesihatan.",
  nutritionDisclaimer: "Nilai nutrisi adalah anggaran berdasarkan ramuan dan hidangan standard.",
  showNutrition: "Lihat Fakta Nutrisi",
  hideNutrition: "Tutup Fakta Nutrisi"
};

const App: React.FC = () => {
  const [language, setLanguage] = useState<LanguageCode>('ms');
  const [uiText, setUiText] = useState<UiText>(DEFAULT_UI_TEXT_MS);
  const [ingredients, setIngredients] = useState<string>('');
  
  const [originalRecipe, setOriginalRecipe] = useState<Recipe | null>(null);
  const [recipe, setRecipe] = useState<Recipe | null>(null);
  const [recipeList, setRecipeList] = useState<RecipeList | null>(null);

  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [loadingType, setLoadingType] = useState<'generate' | 'search'>('generate');
  const [isTranslating, setIsTranslating] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [showTips, setShowTips] = useState<boolean>(true);
  const [generationCount, setGenerationCount] = useState<number | null>(null);
  const [isFeedbackOpen, setIsFeedbackOpen] = useState(false);
  const [isAdminOpen, setIsAdminOpen] = useState(false);
  const [history, setHistory] = useState<Recipe[]>([]);
  
  // Chat Widget State
  const [isChatOpen, setIsChatOpen] = useState(false);
  const [startLiveChat, setStartLiveChat] = useState(false);
  const [showSearchFallback, setShowSearchFallback] = useState(false);
  const [isHistoryOpen, setIsHistoryOpen] = useState(false);
  const [cooldown, setCooldown] = useState(0);

  // PWA Install Prompt State
  const [deferredPrompt, setDeferredPrompt] = useState<any>(null);
  const [isInstallable, setIsInstallable] = useState(false);

  useEffect(() => {
    const handler = (e: Event) => {
      e.preventDefault(); // Prevent Chrome default mini-infobar
      setDeferredPrompt(e);
      setIsInstallable(true);
    };
    window.addEventListener('beforeinstallprompt', handler);
    window.addEventListener('appinstalled', () => {
      setIsInstallable(false);
      setDeferredPrompt(null);
    });
    return () => window.removeEventListener('beforeinstallprompt', handler);
  }, []);

  const installApp = async () => {
    if (!deferredPrompt) return;
    deferredPrompt.prompt();
    const { outcome } = await deferredPrompt.userChoice;
    if (outcome === 'accepted') {
      setIsInstallable(false);
    }
    setDeferredPrompt(null);
  };
  useEffect(() => {
    // Fetch initial count
    const fetchCount = async () => {
      try {
        const count = await getGenerationCount();
        setGenerationCount(count);
      } catch (e) {
        console.error("Failed to fetch generation count:", e);
      }
    };
    fetchCount();

    // Initial keep-alive ping
    keepAlive();

    // Set up interval to ping every 5 minutes (300000 ms) while the app is open
    const heartbeatInterval = setInterval(() => {
      keepAlive();
    }, 300000);

    // Load History
    const savedHistory = localStorage.getItem('toma_recipe_history');
    if (savedHistory) {
      try {
        setHistory(JSON.parse(savedHistory));
      } catch (e) {
        console.error("Failed to parse history", e);
      }
    }

    return () => clearInterval(heartbeatInterval);
  }, []);

  useEffect(() => {
    if (cooldown > 0) {
      const timer = setTimeout(() => setCooldown(cooldown - 1), 1000);
      return () => clearTimeout(timer);
    }
  }, [cooldown]);

  const saveToHistory = (newRecipe: Recipe) => {
    setHistory(prev => {
      // Remove duplicates by name
      const filtered = prev.filter(r => r.recipeName !== newRecipe.recipeName);
      const updated = [newRecipe, ...filtered].slice(0, 15); // Keep last 15
      localStorage.setItem('toma_recipe_history', JSON.stringify(updated));
      return updated;
    });
  };

  const handleClearHistory = () => {
    setHistory([]);
    localStorage.removeItem('toma_recipe_history');
  };

  const handleDeleteHistoryItem = (recipeNameToDelete: string) => {
    setHistory(prev => {
      const updated = prev.filter(r => r.recipeName !== recipeNameToDelete);
      localStorage.setItem('toma_recipe_history', JSON.stringify(updated));
      return updated;
    });
  };

  const handleHistorySelect = (selectedRecipe: Recipe) => {
    // Determine language based on content (simple check) or just force it to current UI text
    // Since history saves the recipe in the language it was generated in.
    setRecipe(selectedRecipe);
    setOriginalRecipe(selectedRecipe); // Assumption: history item is valid
    
    // Scroll to display
    setTimeout(() => {
        const element = document.getElementById('recipe-display');
        if (element) element.scrollIntoView({ behavior: 'smooth' });
    }, 100);
  };

  const handleLanguageChange = useCallback(async (newLangCode: LanguageCode) => {
    if (newLangCode === language) return;

    setLanguage(newLangCode);
    const targetLanguage = LANGUAGES.find(l => l.code === newLangCode);
    if (!targetLanguage) return;

    setIsTranslating(true);
    try {
      if (newLangCode === 'en') {
        setUiText(DEFAULT_UI_TEXT_EN);
        if (originalRecipe) setRecipe(originalRecipe);
      } else if (newLangCode === 'ms') {
        setUiText(DEFAULT_UI_TEXT_MS);
        if (originalRecipe) {
           const translatedRecipe = await translateContent(originalRecipe, 'Bahasa Melayu');
           setRecipe(translatedRecipe);
        }
      } else {
        const contentToTranslate = {
          ...DEFAULT_UI_TEXT_EN,
          ...(originalRecipe || {})
        };
        
        const translatedContent = await translateContent(contentToTranslate, targetLanguage.name);

        const newUiText: Partial<UiText> = {};
        for (const key in DEFAULT_UI_TEXT_EN) {
          if (translatedContent[key]) {
            (newUiText as any)[key] = translatedContent[key];
          }
        }
        setUiText(newUiText as UiText);

        if (originalRecipe) {
          const newRecipe: Partial<Recipe> = {};
           for (const key in originalRecipe) {
            if (translatedContent[key]) {
              (newRecipe as any)[key] = translatedContent[key];
            }
          }
          setRecipe(newRecipe as Recipe);
        }
      }
    } catch(e) {
      console.error(e);
      const errorMessage = e instanceof Error ? e.message : 'An unknown error occurred.';
      setError(`Translation failed: ${errorMessage}`);
    } finally {
      setIsTranslating(false);
    }
  }, [language, originalRecipe]);

  const generateRecipeLogic = useCallback(async (inputIngredients: string) => {
    if (!inputIngredients.trim()) {
      setError(uiText.errorIngredients);
      return;
    }
    
    const isSearch = /resepi|recipe|cara|how to|masak|buat/i.test(inputIngredients) || inputIngredients.split(',').length <= 2;
    setLoadingType(isSearch ? 'search' : 'generate');

    setShowTips(false);
    setIsLoading(true);
    setError(null);
    setShowSearchFallback(false);
    setRecipe(null);
    setRecipeList(null);
    setOriginalRecipe(null);
    
    // Scroll to input if needed (optional)
    const element = document.getElementById('root');
    if (element) element.scrollIntoView({ behavior: 'smooth' });

    try {
      // OPTIMIZATION: Smart Normalization for Cache
      const normalized = inputIngredients.toLowerCase()
          .split(/[\s,]+/)
          .filter(w => w.length > 2 && !['dan', 'and', 'with', 'dengan', 'recipe', 'resepi', 'masak', 'buat'].includes(w))
          .sort()
          .join('-');
      const recipeId = normalized || inputIngredients.toLowerCase().trim().replace(/[^a-z0-9]/g, '-').substring(0, 100);

      let generatedData = await getCachedRecipe(recipeId);
      
      if (!generatedData) {
          // If not in cache, call API
          generatedData = await generateRecipe(inputIngredients);
          
          // Check if it's a list or a single recipe
          if ('results' in generatedData) {
              setRecipeList(generatedData as RecipeList);
              setIsLoading(false);
              return;
          }
          
          // Only cache single recipes
          if (generatedData && (generatedData as Recipe).recipeName) {
              saveRecipeToCache(recipeId, generatedData, inputIngredients);
          }
          setCooldown(15); // 15 seconds cooldown after API call
      } else {
          console.log("Loaded recipe from global cache");
          generatedData = normalizeGenAIResponse(generatedData);
      }

      const generatedRecipe = generatedData as Recipe;
      setOriginalRecipe(generatedRecipe);
      
      // After successful generation, record it and update count
      recordGeneration();
      setGenerationCount(prev => (prev !== null ? prev + 1 : 1));

      let finalRecipe = generatedRecipe;

      if (language === 'en') {
        setRecipe(generatedRecipe);
      } else {
        const targetLanguage = LANGUAGES.find(l => l.code === language);
        if (targetLanguage) {
          try {
            const translatedRecipe = await translateContent(generatedRecipe, targetLanguage.name);
            setRecipe(translatedRecipe);
            finalRecipe = translatedRecipe;
          } catch (translationError) {
            console.error("Translation failed, showing original recipe:", translationError);
            setRecipe(generatedRecipe);
            finalRecipe = generatedRecipe;
          }
        } else {
            setRecipe(generatedRecipe); // Fallback to english
        }
      }
      
      // Save to history (save the displayed language version for convenience)
      saveToHistory(finalRecipe);

    } catch (e) {
      console.error(e);
      setCooldown(5); // 5 seconds cooldown on error to prevent spamming
      const errorMessage = e instanceof Error ? e.message : 'An unknown error occurred.';
      
      if (errorMessage === 'RATE_LIMIT_REACHED') {
          setError(language === 'ms' 
            ? "Maaf, Chef Toma sedang sibuk (had penggunaan dicapai). Sila cuba cari di Google:" 
            : "Sorry, Chef Toma is busy (usage limit reached). Please try searching on Google:");
          setShowSearchFallback(true);
      } else {
          setError(`${uiText.errorPrefix} ${errorMessage}`);
      }
    } finally {
      setIsLoading(false);
    }
  }, [language, uiText]);

  const handleGenerateRecipe = () => {
    generateRecipeLogic(ingredients);
  };

  // Called by ChatWidget to auto-fill and generate
  const handleAutoGenerate = useCallback((detectedIngredients: string) => {
      setIngredients(detectedIngredients);
      generateRecipeLogic(detectedIngredients);
  }, [generateRecipeLogic]);

  const handleReset = () => {
    setIngredients('');
    setRecipe(null);
    setRecipeList(null);
    setOriginalRecipe(null);
    setError(null);
    setShowSearchFallback(false);
    setShowTips(true);
  };

  const handleRecipeSelect = (selected: RecipeSearchResult) => {
      // When selecting from list, treat it as a new generation request for that specific title
      // But we can keep the list visible in background or just replace it?
      // User asked for "Back button", so we should probably hide list and show recipe, then allow back.
      // Actually, simplest is to just call generateRecipeLogic with the title.
      // BUT we need to handle "Back".
      // Let's just generate it. If user wants back, they can search again? 
      // Or better: We can store the list in state, and if we are viewing a recipe that came from a list, show back button.
      // For now, let's just generate. The "Back" button logic requires more complex state management (navigation stack).
      // Let's implement a simple "Back to Results" if recipeList is present.
      
      generateRecipeLogic(selected.title);
  };

  const handleBackToResults = () => {
      setRecipe(null);
      setOriginalRecipe(null);
      // recipeList is already there, so it will show up
      setTimeout(() => {
          const element = document.getElementById('root');
          if (element) element.scrollIntoView({ behavior: 'smooth' });
      }, 100);
  };

  const handleChatToggle = (isOpen: boolean) => {
    setIsChatOpen(isOpen);
    if (!isOpen) {
      setStartLiveChat(false); // Reset live mode trigger when closing
    }
  };

  return (
    // Update main container to remove bg color so decorations show through
    <div className="min-h-screen relative text-gray-800 antialiased flex flex-col overflow-x-hidden">
      
      {/* Animated Background */}
      <BackgroundDecorations />

      {/* PWA Install Banner */}
      {isInstallable && (
        <div className="fixed top-0 left-0 right-0 z-50 p-3 bg-emerald-600 text-white flex items-center justify-between shadow-lg animate-fadeInUp">
          <div className="flex items-center gap-3">
            <span className="text-2xl">🍅</span>
            <p className="text-sm font-medium">{uiText.installMessage}</p>
          </div>
          <div className="flex items-center gap-2">
            <button 
              onClick={installApp}
              className="px-4 py-1.5 bg-white text-emerald-600 rounded-full text-sm font-bold hover:bg-emerald-50 transition-colors"
            >
              {uiText.installButton}
            </button>
            <button 
              onClick={() => setIsInstallable(false)}
              className="p-1 hover:bg-emerald-700 rounded-full transition-colors"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
              </svg>
            </button>
          </div>
        </div>
      )}

      <div className="absolute top-0 right-0 p-4 z-10 flex items-center gap-2">
        <LanguageSelector 
          currentLanguage={language} 
          languages={LANGUAGES}
          onChange={handleLanguageChange}
          isDisabled={isTranslating || isLoading}
        />
      </div>

      {/* History Toggle Button */}
      <button
        onClick={() => setIsHistoryOpen(true)}
        className="absolute top-4 left-4 z-10 p-2 bg-white/80 backdrop-blur-sm border border-gray-200 rounded-xl shadow-sm hover:shadow-md hover:bg-white transition-all text-gray-700"
        aria-label="Open History"
      >
        <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
        </svg>
      </button>

      <HistoryList 
        history={history} 
        uiText={uiText} 
        onSelect={handleHistorySelect} 
        onClear={handleClearHistory}
        onDelete={handleDeleteHistoryItem}
        isOpen={isHistoryOpen}
        onClose={() => setIsHistoryOpen(false)}
      />
      
      {/* Reduced py-6 for mobile, md:py-20 for desktop */}
      <main className="container mx-auto px-4 py-6 md:py-20 flex-grow relative z-0">
        <Header title={uiText.headerTitle} subtitle={uiText.headerSubtitle} />
        
        <div className="max-w-2xl mx-auto mt-6 md:mt-10">
          {/* Glass Card for Input */}
          <div className="bg-white/60 backdrop-blur-xl p-4 md:p-8 rounded-2xl shadow-xl border border-white/40 ring-1 ring-white/50">
            <IngredientInput
              ingredients={ingredients}
              onIngredientsChange={setIngredients}
              onGenerate={handleGenerateRecipe}
              onReset={handleReset}
              isLoading={isLoading}
              loadingType={loadingType}
              cooldown={cooldown}
              uiText={uiText}
              currentLanguage={language}
            />

            {error && (
              <div className="mt-4 text-center">
                <p className="text-red-600 font-semibold bg-red-50/50 p-2 rounded-lg border border-red-100 mb-2">{error}</p>
                {showSearchFallback && (
                  <a 
                    href={`https://www.google.com/search?q=resepi+${encodeURIComponent(ingredients)}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-full hover:bg-blue-700 transition-colors font-medium"
                  >
                    <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z"/>
                    </svg>
                    {language === 'ms' ? 'Cari di Google' : 'Search on Google'}
                  </a>
                )}
              </div>
            )}
          </div>

          <UsageTips isVisible={showTips} tips={uiText.usageTips} />
        </div>


        <AnimatePresence mode="wait">
          {(isLoading || isTranslating) && (
            <motion.div
              key="loading"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            >
              <LoadingSpinner messages={isLoading ? uiText.loadingMessages : [uiText.translatingMessage]} />
            </motion.div>
          )}

          {recipeList && !recipe && !isLoading && (
            <motion.div
              key="list"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
            >
              <RecipeListDisplay 
                recipeList={recipeList}
                onSelect={handleRecipeSelect}
                uiText={uiText}
              />
            </motion.div>
          )}

          {recipe && !isLoading && !isTranslating && (
            <motion.div
              key="recipe"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              transition={{ type: "spring", damping: 20, stiffness: 100 }}
              id="recipe-display"
            >
              {recipeList && (
                <button 
                  onClick={handleBackToResults}
                  className="mb-4 flex items-center gap-2 text-emerald-600 font-medium hover:text-emerald-700 transition-colors px-4"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                    <path fillRule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clipRule="evenodd" />
                  </svg>
                  {uiText.backToResults}
                </button>
              )}
              <RecipeDisplay 
                recipe={recipe} 
                uiText={uiText}
              />
            </motion.div>
          )}
        </AnimatePresence>
      </main>
      
      {generationCount !== null && <GenerationCounter count={generationCount} uiText={uiText} />}
      
      <Footer 
        uiText={uiText} 
        onOpenFeedback={() => setIsFeedbackOpen(true)}
        onOpenAdmin={() => setIsAdminOpen(true)} 
      />
      
      <ScrollToTopButton isChatOpen={isChatOpen} />
      
      {/* Chat Widget integrated here */}
      <ChatWidget 
        currentLanguage={language} 
        languages={LANGUAGES} 
        onAutoGenerate={handleAutoGenerate}
        isOpen={isChatOpen}
        onToggle={handleChatToggle}
        startLiveOnOpen={startLiveChat}
      />

      {isFeedbackOpen && (
        <FeedbackModal 
          uiText={uiText} 
          onClose={() => setIsFeedbackOpen(false)} 
        />
      )}

      {isAdminOpen && (
        <AdminModal onClose={() => setIsAdminOpen(false)} />
      )}
    </div>
  );
};

export default App;
